<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CD059" name="Smoke.NewInstance_BulkEntryTemplate_UptoDispatch" tests="1" failures="1" timestamp="20 Jul 2018 06:44:35 GMT" time="14.391" errors="0">
  <testcase name="newInstance_BulkEntryROAR_PreliminaryAndFinal_UptoDispatch_Growth_TwoAnalyteFlow" time="14.391" classname="Smoke.NewInstance_BulkEntryTemplate_UptoDispatch">
    <failure type="java.lang.AssertionError" message="***Registration --&gt; Alert msg not displayed as expected.*** expected [Saved successfully] but found [Please Select Guardian Title]">
      <![CDATA[java.lang.AssertionError: ***Registration --> Alert msg not displayed as expected.*** expected [Saved successfully] but found [Please Select Guardian Title]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at Smoke.NewInstance_BulkEntryTemplate_UptoDispatch.newInstance_BulkEntryROAR_PreliminaryAndFinal_UptoDispatch_Growth_TwoAnalyteFlow(NewInstance_BulkEntryTemplate_UptoDispatch.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- newInstance_BulkEntryROAR_PreliminaryAndFinal_UptoDispatch_Growth_TwoAnalyteFlow -->
</testsuite> <!-- Smoke.NewInstance_BulkEntryTemplate_UptoDispatch -->
