<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="58934" started-at="2018-07-20T09:51:33Z" finished-at="2018-07-20T09:52:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="58934" started-at="2018-07-20T09:51:33Z" finished-at="2018-07-20T09:52:31Z">
      <class name="Smoke.NewInstance_InvoiceGeneration">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Smoke.NewInstance_InvoiceGeneration@604ed9f0]" name="beforeMethod" is-config="true" duration-ms="8245" started-at="2018-07-20T15:21:33Z" finished-at="2018-07-20T15:21:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="newInstance_Canceling2of4ServicesWithBothBillAndItemLevelDiscountInPercentageAndPatientNotPaidTheBill()[pri:1, instance:Smoke.NewInstance_InvoiceGeneration@604ed9f0]" name="newInstance_Canceling2of4ServicesWithBothBillAndItemLevelDiscountInPercentageAndPatientNotPaidTheBill" duration-ms="50025" started-at="2018-07-20T15:21:41Z" finished-at="2018-07-20T15:22:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [200.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [200.00]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Smoke.NewInstance_InvoiceGeneration.newInstance_Canceling2of4ServicesWithBothBillAndItemLevelDiscountInPercentageAndPatientNotPaidTheBill(NewInstance_InvoiceGeneration.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newInstance_Canceling2of4ServicesWithBothBillAndItemLevelDiscountInPercentageAndPatientNotPaidTheBill -->
        <test-method status="PASS" signature="updateResult(org.testng.ITestResult)[pri:0, instance:Smoke.NewInstance_InvoiceGeneration@604ed9f0]" name="updateResult" is-config="true" duration-ms="595" started-at="2018-07-20T15:22:31Z" finished-at="2018-07-20T15:22:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=newInstance_Canceling2of4ServicesWithBothBillAndItemLevelDiscountInPercentageAndPatientNotPaidTheBill status=FAILURE method=NewInstance_InvoiceGeneration.newInstance_Canceling2of4ServicesWithBothBillAndItemLevelDiscountInPercentageAndPatientNotPaidTheBill()[pri:1, instance:Smoke.NewInstance_InvoiceGeneration@604ed9f0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateResult -->
      </class> <!-- Smoke.NewInstance_InvoiceGeneration -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
